"""Constants for Ring Extended integration."""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Callable

from homeassistant.components.sensor import (
    SensorDeviceClass,
    SensorEntityDescription,
    SensorStateClass,
)
from homeassistant.const import (
    PERCENTAGE,
    SIGNAL_STRENGTH_DECIBELS_MILLIWATT,
    UnitOfTime,
    UnitOfElectricPotential,
    UnitOfDataRate,
)

DOMAIN = "ring_extended"

# Device families to scan
DEVICE_FAMILIES = ["doorbells", "stickup_cams", "chimes", "other"]

# Sensor categories for config flow
SENSOR_CATEGORIES = [
    "health",
    "power",
    "firmware",
    "video",
    "audio",
    "motion",
    "cv_detection",
    "cv_paid",
    "other_paid",
    "notifications",
    "recording",
    "floodlight",
    "radar",
    "local_processing",
    "features",
    "device_status",
]

CATEGORY_NAMES = {
    "health": "Health & Connectivity",
    "power": "Power & Battery",
    "firmware": "Firmware",
    "video": "Video & Streaming",
    "audio": "Audio",
    "motion": "Motion Detection",
    "cv_detection": "CV Detection Types",
    "cv_paid": "CV Paid Features",
    "other_paid": "Other Paid Features",
    "notifications": "Notifications",
    "recording": "Recording & Storage",
    "floodlight": "Floodlight",
    "radar": "Radar / Bird's Eye",
    "local_processing": "Local Processing",
    "features": "Feature Eligibility",
    "device_status": "Device Status",
}


def get_nested(data: dict, path: str, default: Any = None) -> Any:
    """Safely get nested dictionary value using dot notation."""
    if data is None:
        return default
    keys = path.split(".")
    for key in keys:
        if isinstance(data, dict):
            data = data.get(key)
        else:
            return default
        if data is None:
            return default
    return data


def _format_uptime(seconds: int | None) -> str | None:
    """Convert seconds to human-readable uptime format."""
    if seconds is None:
        return None
    try:
        seconds = int(seconds)
        days = seconds // 86400
        hours = (seconds % 86400) // 3600
        mins = (seconds % 3600) // 60
        return f"{days}d {hours}h {mins}m"
    except (ValueError, TypeError):
        return None


def _value_exists(attrs: dict, path: str) -> bool:
    """Check if a value exists at the given path."""
    return get_nested(attrs, path) is not None


def _unix_to_datetime(timestamp: int | None) -> datetime | None:
    """Convert Unix timestamp to datetime with timezone."""
    if timestamp is None:
        return None
    try:
        return datetime.fromtimestamp(timestamp, tz=timezone.utc)
    except (ValueError, TypeError, OSError):
        return None


def _parse_throughput_to_mbps(value: str | int | float | None) -> float | None:
    """Parse throughput value to Mbps.

    Ring API returns values like '28972 Kbps' as strings.
    Convert to numeric Mbps value.
    """
    if value is None:
        return None
    try:
        if isinstance(value, (int, float)):
            return float(value)
        # Parse string like "28972 Kbps"
        value_str = str(value).strip()
        parts = value_str.split()
        if not parts:
            return None
        num = float(parts[0])
        # Convert Kbps to Mbps if needed
        if len(parts) > 1 and "kbps" in parts[1].lower():
            return round(num / 1000, 2)
        return num
    except (ValueError, TypeError, IndexError):
        return None


@dataclass(frozen=True, kw_only=True)
class RingExtendedSensorDescription(SensorEntityDescription):
    """Describes Ring extended sensor entity."""

    category: str = "health"
    attr_path: str = ""
    value_fn: Callable[[dict], Any] | None = None
    available_fn: Callable[[dict], bool] | None = None

    def get_value(self, attrs: dict) -> Any:
        """Get the sensor value from device attributes."""
        if self.value_fn is not None:
            return self.value_fn(attrs)
        return get_nested(attrs, self.attr_path)

    def is_available(self, attrs: dict) -> bool:
        """Check if sensor is available."""
        if self.available_fn is not None:
            return self.available_fn(attrs)
        return _value_exists(attrs, self.attr_path)


# Health & Connectivity sensors
HEALTH_SENSORS: tuple[RingExtendedSensorDescription, ...] = (
    RingExtendedSensorDescription(
        key="rssi",
        translation_key="rssi",
        native_unit_of_measurement=SIGNAL_STRENGTH_DECIBELS_MILLIWATT,
        device_class=SensorDeviceClass.SIGNAL_STRENGTH,
        state_class=SensorStateClass.MEASUREMENT,
        category="health",
        attr_path="health.rssi",
        entity_registry_enabled_default=True,
    ),
    RingExtendedSensorDescription(
        key="rssi_category",
        translation_key="rssi_category",
        category="health",
        attr_path="health.rssi_category",
    ),
    RingExtendedSensorDescription(
        key="connected",
        translation_key="connected",
        category="health",
        attr_path="health.connected",
    ),
    RingExtendedSensorDescription(
        key="packet_loss",
        translation_key="packet_loss",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        category="health",
        attr_path="health.packet_loss",
    ),
    RingExtendedSensorDescription(
        key="packet_loss_category",
        translation_key="packet_loss_category",
        category="health",
        attr_path="health.packet_loss_category",
    ),
    RingExtendedSensorDescription(
        key="bandwidth",
        translation_key="bandwidth",
        native_unit_of_measurement="kbps",
        state_class=SensorStateClass.MEASUREMENT,
        category="health",
        attr_path="health.bandwidth",
    ),
    RingExtendedSensorDescription(
        key="current_bandwidth_mb",
        translation_key="current_bandwidth_mb",
        native_unit_of_measurement=UnitOfDataRate.MEGABITS_PER_SECOND,
        device_class=SensorDeviceClass.DATA_RATE,
        state_class=SensorStateClass.MEASUREMENT,
        category="health",
        attr_path="health.current_bandwidth_mb",
    ),
    RingExtendedSensorDescription(
        key="egress_tx_rate",
        translation_key="egress_tx_rate",
        native_unit_of_measurement=UnitOfDataRate.MEGABITS_PER_SECOND,
        device_class=SensorDeviceClass.DATA_RATE,
        state_class=SensorStateClass.MEASUREMENT,
        category="health",
        attr_path="health.egress_tx_rate",
        value_fn=lambda attrs: float(v) if (v := get_nested(attrs, "health.egress_tx_rate")) else None,
    ),
    RingExtendedSensorDescription(
        key="egress_tx_rate_category",
        translation_key="egress_tx_rate_category",
        category="health",
        attr_path="health.egress_tx_rate_category",
    ),
    RingExtendedSensorDescription(
        key="wifi_channel",
        translation_key="wifi_channel",
        category="health",
        attr_path="health.channel",
    ),
    RingExtendedSensorDescription(
        key="network_connection_value",
        translation_key="network_connection_value",
        category="health",
        attr_path="health.network_connection_value",
    ),
    RingExtendedSensorDescription(
        key="sidewalk_connection",
        translation_key="sidewalk_connection",
        category="health",
        attr_path="health.sidewalk_connection",
    ),
    RingExtendedSensorDescription(
        key="uptime_sec",
        translation_key="uptime_sec",
        native_unit_of_measurement=UnitOfTime.SECONDS,
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.TOTAL_INCREASING,
        category="health",
        attr_path="health.uptime_sec",
    ),
    RingExtendedSensorDescription(
        key="uptime_formatted",
        translation_key="uptime_formatted",
        category="health",
        attr_path="health.uptime_sec",
        value_fn=lambda attrs: _format_uptime(get_nested(attrs, "health.uptime_sec")),
    ),
    RingExtendedSensorDescription(
        key="last_update_time",
        translation_key="last_update_time",
        device_class=SensorDeviceClass.TIMESTAMP,
        category="health",
        attr_path="health.last_update_time",
        value_fn=lambda attrs: _unix_to_datetime(get_nested(attrs, "health.last_update_time")),
    ),
    RingExtendedSensorDescription(
        key="wifi_is_ring_network",
        translation_key="wifi_is_ring_network",
        category="health",
        attr_path="health.wifi_is_ring_network",
    ),
    RingExtendedSensorDescription(
        key="current_bandwidth_raw",
        translation_key="current_bandwidth_raw",
        native_unit_of_measurement="kbps",
        state_class=SensorStateClass.MEASUREMENT,
        category="health",
        attr_path="health.current_bandwidth",
    ),
    RingExtendedSensorDescription(
        key="current_bandwidth_category",
        translation_key="current_bandwidth_category",
        category="health",
        attr_path="health.current_bandwidth_category",
    ),
    RingExtendedSensorDescription(
        key="bandwidth_last_time",
        translation_key="bandwidth_last_time",
        device_class=SensorDeviceClass.TIMESTAMP,
        category="health",
        attr_path="health.bandwidth_last_time",
        value_fn=lambda attrs: _unix_to_datetime(get_nested(attrs, "health.bandwidth_last_time")),
    ),
    RingExtendedSensorDescription(
        key="device_type",
        translation_key="device_type",
        category="health",
        attr_path="health.device_type",
    ),
    RingExtendedSensorDescription(
        key="external_connection_health",
        translation_key="external_connection_health",
        category="health",
        attr_path="health.external_connection",
    ),
    RingExtendedSensorDescription(
        key="fast_ping_hop1_score",
        translation_key="fast_ping_hop1_score",
        category="health",
        attr_path="health.fast_ping_hop1_score",
    ),
    RingExtendedSensorDescription(
        key="iperf_tcp_throughput",
        translation_key="iperf_tcp_throughput",
        native_unit_of_measurement="Mbps",
        state_class=SensorStateClass.MEASUREMENT,
        category="health",
        attr_path="health.iperf_tcp_throughput",
        value_fn=lambda attrs: _parse_throughput_to_mbps(get_nested(attrs, "health.iperf_tcp_throughput")),
    ),
    RingExtendedSensorDescription(
        key="privacy_cover_enabled",
        translation_key="privacy_cover_enabled",
        category="health",
        attr_path="health.privacy_cover_enabled",
    ),
    RingExtendedSensorDescription(
        key="rss_connected",
        translation_key="rss_connected",
        category="health",
        attr_path="health.rss_connected",
    ),
    RingExtendedSensorDescription(
        key="second_battery_percentage_category",
        translation_key="second_battery_percentage_category",
        category="health",
        attr_path="health.second_battery_percentage_category",
    ),
    RingExtendedSensorDescription(
        key="second_battery_voltage_category",
        translation_key="second_battery_voltage_category",
        category="health",
        attr_path="health.second_battery_voltage_category",
    ),
    RingExtendedSensorDescription(
        key="stream_profile",
        translation_key="stream_profile",
        category="health",
        attr_path="health.stream_profile",
    ),
    RingExtendedSensorDescription(
        key="transformer_score",
        translation_key="transformer_score",
        category="health",
        attr_path="health.transformer_score",
    ),
    RingExtendedSensorDescription(
        key="transformer_status",
        translation_key="transformer_status",
        category="health",
        attr_path="health.transformer_status",
    ),
    RingExtendedSensorDescription(
        key="tx_rate",
        translation_key="tx_rate",
        native_unit_of_measurement="Mbps",
        state_class=SensorStateClass.MEASUREMENT,
        category="health",
        attr_path="health.tx_rate",
    ),
    RingExtendedSensorDescription(
        key="video_packets_total",
        translation_key="video_packets_total",
        state_class=SensorStateClass.TOTAL_INCREASING,
        category="health",
        attr_path="health.video_packets_total",
    ),
    RingExtendedSensorDescription(
        key="status_time",
        translation_key="status_time",
        category="health",
        attr_path="health.status_time",
    ),
    RingExtendedSensorDescription(
        key="alert_connection",
        translation_key="alert_connection",
        category="health",
        attr_path="alerts.connection",
    ),
    RingExtendedSensorDescription(
        key="alert_ota_status",
        translation_key="alert_ota_status",
        category="health",
        attr_path="alerts.ota_status",
    ),
)

# Power & Battery sensors
POWER_SENSORS: tuple[RingExtendedSensorDescription, ...] = (
    RingExtendedSensorDescription(
        key="battery_percentage",
        translation_key="battery_percentage",
        native_unit_of_measurement=PERCENTAGE,
        device_class=SensorDeviceClass.BATTERY,
        state_class=SensorStateClass.MEASUREMENT,
        category="power",
        attr_path="health.battery_percentage",
    ),
    RingExtendedSensorDescription(
        key="battery_percentage_category",
        translation_key="battery_percentage_category",
        category="power",
        attr_path="health.battery_percentage_category",
    ),
    RingExtendedSensorDescription(
        key="battery_voltage",
        translation_key="battery_voltage",
        native_unit_of_measurement="mV",
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        category="power",
        attr_path="health.battery_voltage",
    ),
    RingExtendedSensorDescription(
        key="battery_voltage_category",
        translation_key="battery_voltage_category",
        category="power",
        attr_path="health.battery_voltage_category",
    ),
    RingExtendedSensorDescription(
        key="battery_present",
        translation_key="battery_present",
        category="power",
        attr_path="health.battery_present",
    ),
    RingExtendedSensorDescription(
        key="battery_save",
        translation_key="battery_save",
        category="power",
        attr_path="health.battery_save",
    ),
    RingExtendedSensorDescription(
        key="battery_error",
        translation_key="battery_error",
        category="power",
        attr_path="health.battery_error",
    ),
    RingExtendedSensorDescription(
        key="ac_power",
        translation_key="ac_power",
        category="power",
        attr_path="health.ac_power",
        value_fn=lambda attrs: bool(int(v)) if (v := get_nested(attrs, "health.ac_power")) is not None else None,
    ),
    RingExtendedSensorDescription(
        key="transformer_voltage",
        translation_key="transformer_voltage",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        category="power",
        attr_path="health.transformer_voltage",
    ),
    RingExtendedSensorDescription(
        key="transformer_voltage_category",
        translation_key="transformer_voltage_category",
        category="power",
        attr_path="health.transformer_voltage_category",
    ),
    RingExtendedSensorDescription(
        key="ext_power_state",
        translation_key="ext_power_state",
        category="power",
        attr_path="health.ext_power_state",
    ),
    RingExtendedSensorDescription(
        key="run_mode",
        translation_key="run_mode",
        category="power",
        attr_path="health.run_mode",
    ),
    RingExtendedSensorDescription(
        key="pref_run_mode",
        translation_key="pref_run_mode",
        category="power",
        attr_path="health.pref_run_mode",
    ),
    RingExtendedSensorDescription(
        key="battery_life",
        translation_key="battery_life",
        native_unit_of_measurement=PERCENTAGE,
        device_class=SensorDeviceClass.BATTERY,
        state_class=SensorStateClass.MEASUREMENT,
        category="power",
        attr_path="battery_life",
    ),
    RingExtendedSensorDescription(
        key="ext_power_state_root",
        translation_key="ext_power_state_root",
        category="power",
        attr_path="ext_power_state",
    ),
    RingExtendedSensorDescription(
        key="external_connection",
        translation_key="external_connection",
        category="power",
        attr_path="external_connection",
    ),
    RingExtendedSensorDescription(
        key="power_mode",
        translation_key="power_mode",
        category="power",
        attr_path="settings.power_mode",
    ),
    RingExtendedSensorDescription(
        key="powered_on",
        translation_key="powered_on",
        category="power",
        attr_path="settings.powered_on",
    ),
)

# Firmware sensors
FIRMWARE_SENSORS: tuple[RingExtendedSensorDescription, ...] = (
    RingExtendedSensorDescription(
        key="firmware_version",
        translation_key="firmware_version",
        category="firmware",
        attr_path="health.firmware_version",
    ),
    RingExtendedSensorDescription(
        key="firmware_version_status",
        translation_key="firmware_version_status",
        category="firmware",
        attr_path="health.firmware_version_status",
    ),
    RingExtendedSensorDescription(
        key="ota_status",
        translation_key="ota_status",
        category="firmware",
        attr_path="health.ota_status",
    ),
    RingExtendedSensorDescription(
        key="firmware_avg_bitrate",
        translation_key="firmware_avg_bitrate",
        native_unit_of_measurement="kbps",
        state_class=SensorStateClass.MEASUREMENT,
        category="firmware",
        attr_path="health.firmware_avg_bitrate",
        value_fn=lambda attrs: int(v) if (v := get_nested(attrs, "health.firmware_avg_bitrate")) else None,
    ),
    RingExtendedSensorDescription(
        key="firmware_version_root",
        translation_key="firmware_version_root",
        category="firmware",
        attr_path="firmware_version",
    ),
)

# Video & Streaming sensors
VIDEO_SENSORS: tuple[RingExtendedSensorDescription, ...] = (
    RingExtendedSensorDescription(
        key="vod_enabled",
        translation_key="vod_enabled",
        category="video",
        attr_path="health.vod_enabled",
    ),
    RingExtendedSensorDescription(
        key="vod_status",
        translation_key="vod_status",
        category="video",
        attr_path="settings.vod_status",
    ),
    RingExtendedSensorDescription(
        key="vod_suspended",
        translation_key="vod_suspended",
        category="video",
        attr_path="settings.vod_suspended",
    ),
    RingExtendedSensorDescription(
        key="stream_resolution",
        translation_key="stream_resolution",
        category="video",
        attr_path="health.stream_resolution",
    ),
    RingExtendedSensorDescription(
        key="live_view_preset_profile",
        translation_key="live_view_preset_profile",
        category="video",
        attr_path="settings.live_view_preset_profile",
    ),
    RingExtendedSensorDescription(
        key="live_view_disabled",
        translation_key="live_view_disabled",
        category="video",
        attr_path="settings.live_view_disabled",
    ),
    RingExtendedSensorDescription(
        key="extended_live_view",
        translation_key="extended_live_view",
        category="video",
        attr_path="settings.extended_live_view",
    ),
    RingExtendedSensorDescription(
        key="exposure_control",
        translation_key="exposure_control",
        category="video",
        attr_path="settings.exposure_control",
    ),
    RingExtendedSensorDescription(
        key="preroll_enabled",
        translation_key="preroll_enabled",
        category="video",
        attr_path="settings.preroll_enabled",
    ),
    RingExtendedSensorDescription(
        key="max_resolution_mode",
        translation_key="max_resolution_mode",
        category="video",
        attr_path="settings.max_resolution_mode",
    ),
    RingExtendedSensorDescription(
        key="encryption_enabled",
        translation_key="encryption_enabled",
        category="video",
        attr_path="settings.video_settings.encryption_enabled",
    ),
    RingExtendedSensorDescription(
        key="hevc_enabled",
        translation_key="hevc_enabled",
        category="video",
        attr_path="settings.video_settings.hevc_enabled",
    ),
    RingExtendedSensorDescription(
        key="max_digital_zoom_level",
        translation_key="max_digital_zoom_level",
        category="video",
        attr_path="features.video_rendering.max_digital_zoom_level",
    ),
    RingExtendedSensorDescription(
        key="enable_ir",
        translation_key="enable_ir",
        category="video",
        attr_path="settings.enable_ir",
    ),
    RingExtendedSensorDescription(
        key="enable_ir_led",
        translation_key="enable_ir_led",
        category="video",
        attr_path="settings.enable_ir_led",
    ),
    RingExtendedSensorDescription(
        key="ir_led_brightness",
        translation_key="ir_led_brightness",
        category="video",
        attr_path="settings.ir_led_brightness",
    ),
    RingExtendedSensorDescription(
        key="luma_light_threshold",
        translation_key="luma_light_threshold",
        category="video",
        attr_path="settings.luma_light_threshold",
    ),
    RingExtendedSensorDescription(
        key="luma_night_threshold",
        translation_key="luma_night_threshold",
        category="video",
        attr_path="settings.luma_night_threshold",
    ),
    RingExtendedSensorDescription(
        key="stream_profile_setting",
        translation_key="stream_profile_setting",
        category="video",
        attr_path="settings.stream_profile",
    ),
    RingExtendedSensorDescription(
        key="stream_setting",
        translation_key="stream_setting",
        category="video",
        attr_path="settings.stream_setting",
    ),
    RingExtendedSensorDescription(
        key="night_mode",
        translation_key="night_mode",
        category="video",
        attr_path="settings.night_mode",
    ),
    RingExtendedSensorDescription(
        key="camera_location_indoor",
        translation_key="camera_location_indoor",
        category="video",
        attr_path="camera_location_indoor",
    ),
    RingExtendedSensorDescription(
        key="facing_window",
        translation_key="facing_window",
        category="video",
        attr_path="facing_window",
    ),
    RingExtendedSensorDescription(
        key="enable_vod_setting",
        translation_key="enable_vod_setting",
        category="video",
        attr_path="settings.enable_vod",
    ),
    RingExtendedSensorDescription(
        key="ring_media_server_enabled",
        translation_key="ring_media_server_enabled",
        category="video",
        attr_path="settings.server_settings.ring_media_server_enabled",
    ),
    RingExtendedSensorDescription(
        key="ring_media_server_host",
        translation_key="ring_media_server_host",
        category="video",
        attr_path="settings.server_settings.ring_media_server_host",
    ),
    RingExtendedSensorDescription(
        key="encryption_method",
        translation_key="encryption_method",
        category="video",
        attr_path="settings.video_settings.encryption_method",
    ),
    RingExtendedSensorDescription(
        key="max_bitrate_profile",
        translation_key="max_bitrate_profile",
        category="video",
        attr_path="settings.video_settings.max_bitrate_profile",
    ),
    RingExtendedSensorDescription(
        key="recording_24x7_mode",
        translation_key="recording_24x7_mode",
        category="video",
        attr_path="settings.video_settings.recording_24x7_mode",
    ),
    # Video image settings
    RingExtendedSensorDescription(
        key="video_brightness",
        translation_key="video_brightness",
        category="video",
        attr_path="settings.video_settings.brightness",
    ),
    RingExtendedSensorDescription(
        key="video_contrast",
        translation_key="video_contrast",
        category="video",
        attr_path="settings.video_settings.contrast",
    ),
    RingExtendedSensorDescription(
        key="video_saturation",
        translation_key="video_saturation",
        category="video",
        attr_path="settings.video_settings.saturation",
    ),
    RingExtendedSensorDescription(
        key="video_hdr_enabled",
        translation_key="video_hdr_enabled",
        category="video",
        attr_path="settings.video_settings.hdr_enable",
    ),
    RingExtendedSensorDescription(
        key="video_night_color_enabled",
        translation_key="video_night_color_enabled",
        category="video",
        attr_path="settings.video_settings.night_color_enable",
    ),
    RingExtendedSensorDescription(
        key="video_rotate_180",
        translation_key="video_rotate_180",
        category="video",
        attr_path="settings.video_settings.rotate_180_deg",
    ),
    RingExtendedSensorDescription(
        key="video_aspect_ratio",
        translation_key="video_aspect_ratio",
        category="video",
        attr_path="settings.video_settings.aspect_ratio",
    ),
    # Video exposure settings
    RingExtendedSensorDescription(
        key="video_ae_level",
        translation_key="video_ae_level",
        category="video",
        attr_path="settings.video_settings.ae_level",
    ),
    RingExtendedSensorDescription(
        key="video_ae_mode",
        translation_key="video_ae_mode",
        category="video",
        attr_path="settings.video_settings.ae_mode",
    ),
    RingExtendedSensorDescription(
        key="video_exposure_control",
        translation_key="video_exposure_control",
        category="video",
        attr_path="settings.video_settings.exposure_control",
    ),
    # Video clip settings
    RingExtendedSensorDescription(
        key="video_clip_length_max",
        translation_key="video_clip_length_max",
        native_unit_of_measurement=UnitOfTime.SECONDS,
        category="video",
        attr_path="settings.video_settings.clip_length_max",
    ),
    RingExtendedSensorDescription(
        key="video_clip_length_min",
        translation_key="video_clip_length_min",
        native_unit_of_measurement=UnitOfTime.SECONDS,
        category="video",
        attr_path="settings.video_settings.clip_length_min",
    ),
    RingExtendedSensorDescription(
        key="video_clip_length_max_powered",
        translation_key="video_clip_length_max_powered",
        native_unit_of_measurement=UnitOfTime.SECONDS,
        category="video",
        attr_path="settings.video_settings.clip_length_max_powered",
    ),
    RingExtendedSensorDescription(
        key="video_auto_clip_length_enabled",
        translation_key="video_auto_clip_length_enabled",
        category="video",
        attr_path="settings.video_settings.auto_clip_length_enabled",
    ),
    # Video features
    RingExtendedSensorDescription(
        key="video_high_fps_enabled",
        translation_key="video_high_fps_enabled",
        category="video",
        attr_path="settings.video_settings.enable_high_fps",
    ),
    RingExtendedSensorDescription(
        key="video_tsvc_enabled",
        translation_key="video_tsvc_enabled",
        category="video",
        attr_path="settings.video_settings.tsvc_enabled",
    ),
    RingExtendedSensorDescription(
        key="video_encryption_eligibility_mode",
        translation_key="video_encryption_eligibility_mode",
        category="video",
        attr_path="settings.video_settings.encryption_eligibility_mode",
    ),
    # PTZ (Pan/Tilt/Zoom) settings - for Pan Tilt cameras
    RingExtendedSensorDescription(
        key="ptz_auto_scan_pause_ms",
        translation_key="ptz_auto_scan_pause_ms",
        native_unit_of_measurement=UnitOfTime.MILLISECONDS,
        category="video",
        attr_path="settings.ptz_settings.auto_scan.pause_ms",
    ),
    RingExtendedSensorDescription(
        key="ptz_auto_scan_step_size",
        translation_key="ptz_auto_scan_step_size",
        category="video",
        attr_path="settings.ptz_settings.auto_scan.step_size",
    ),
    RingExtendedSensorDescription(
        key="ptz_pan_position_default",
        translation_key="ptz_pan_position_default",
        category="video",
        attr_path="settings.ptz_settings.pan_settings.positions.default",
    ),
    RingExtendedSensorDescription(
        key="ptz_pan_position_max",
        translation_key="ptz_pan_position_max",
        category="video",
        attr_path="settings.ptz_settings.pan_settings.positions.max",
    ),
    RingExtendedSensorDescription(
        key="ptz_pan_position_min",
        translation_key="ptz_pan_position_min",
        category="video",
        attr_path="settings.ptz_settings.pan_settings.positions.min",
    ),
    RingExtendedSensorDescription(
        key="ptz_pan_max_speed",
        translation_key="ptz_pan_max_speed",
        category="video",
        attr_path="settings.ptz_settings.pan_settings.movement.max_speed",
    ),
    RingExtendedSensorDescription(
        key="ptz_pan_step_size",
        translation_key="ptz_pan_step_size",
        category="video",
        attr_path="settings.ptz_settings.pan_settings.movement.step_size",
    ),
    RingExtendedSensorDescription(
        key="ptz_tilt_position_default",
        translation_key="ptz_tilt_position_default",
        category="video",
        attr_path="settings.ptz_settings.tilt_settings.positions.default",
    ),
    RingExtendedSensorDescription(
        key="ptz_tilt_position_max",
        translation_key="ptz_tilt_position_max",
        category="video",
        attr_path="settings.ptz_settings.tilt_settings.positions.max",
    ),
    RingExtendedSensorDescription(
        key="ptz_tilt_position_min",
        translation_key="ptz_tilt_position_min",
        category="video",
        attr_path="settings.ptz_settings.tilt_settings.positions.min",
    ),
    RingExtendedSensorDescription(
        key="ptz_tilt_max_speed",
        translation_key="ptz_tilt_max_speed",
        category="video",
        attr_path="settings.ptz_settings.tilt_settings.movement.max_speed",
    ),
)

# Audio sensors
AUDIO_SENSORS: tuple[RingExtendedSensorDescription, ...] = (
    RingExtendedSensorDescription(
        key="enable_audio_recording",
        translation_key="enable_audio_recording",
        category="audio",
        attr_path="settings.enable_audio_recording",
    ),
    RingExtendedSensorDescription(
        key="doorbell_volume",
        translation_key="doorbell_volume",
        category="audio",
        attr_path="settings.doorbell_volume",
    ),
    RingExtendedSensorDescription(
        key="voice_volume",
        translation_key="voice_volume",
        category="audio",
        attr_path="settings.voice_volume",
    ),
    RingExtendedSensorDescription(
        key="chime_enable",
        translation_key="chime_enable",
        category="audio",
        attr_path="settings.chime_settings.enable",
    ),
    RingExtendedSensorDescription(
        key="chime_duration",
        translation_key="chime_duration",
        native_unit_of_measurement=UnitOfTime.SECONDS,
        device_class=SensorDeviceClass.DURATION,
        category="audio",
        attr_path="settings.chime_settings.duration",
    ),
    RingExtendedSensorDescription(
        key="enable_audio",
        translation_key="enable_audio",
        category="audio",
        attr_path="settings.enable_audio",
    ),
    RingExtendedSensorDescription(
        key="mic_volume",
        translation_key="mic_volume",
        category="audio",
        attr_path="settings.mic_volume",
    ),
    RingExtendedSensorDescription(
        key="enable_live_view_audio_override",
        translation_key="enable_live_view_audio_override",
        category="audio",
        attr_path="settings.audio_settings.enable_live_view_audio_override",
    ),
    RingExtendedSensorDescription(
        key="voice_volume_powered",
        translation_key="voice_volume_powered",
        category="audio",
        attr_path="settings.voice_volume_powered",
    ),
    RingExtendedSensorDescription(
        key="chime_settings_type",
        translation_key="chime_settings_type",
        category="audio",
        attr_path="settings.chime_settings.type",
    ),
)

# Motion Detection sensors
MOTION_SENSORS: tuple[RingExtendedSensorDescription, ...] = (
    RingExtendedSensorDescription(
        key="motion_detection_enabled",
        translation_key="motion_detection_enabled",
        category="motion",
        attr_path="settings.motion_detection_enabled",
    ),
    RingExtendedSensorDescription(
        key="advanced_motion_detection_enabled",
        translation_key="advanced_motion_detection_enabled",
        category="motion",
        attr_path="settings.advanced_motion_detection_enabled",
    ),
    RingExtendedSensorDescription(
        key="advanced_motion_detection_human_only_mode",
        translation_key="advanced_motion_detection_human_only_mode",
        category="motion",
        attr_path="settings.advanced_motion_detection_human_only_mode",
    ),
    RingExtendedSensorDescription(
        key="people_detection_eligible",
        translation_key="people_detection_eligible",
        category="motion",
        attr_path="settings.people_detection_eligible",
    ),
    RingExtendedSensorDescription(
        key="motion_snooze_preset_profile",
        translation_key="motion_snooze_preset_profile",
        category="motion",
        attr_path="settings.motion_snooze_preset_profile",
    ),
    RingExtendedSensorDescription(
        key="loitering_threshold",
        translation_key="loitering_threshold",
        native_unit_of_measurement=UnitOfTime.SECONDS,
        device_class=SensorDeviceClass.DURATION,
        category="motion",
        attr_path="settings.loitering_threshold",
    ),
    RingExtendedSensorDescription(
        key="advanced_motion_zones_enabled",
        translation_key="advanced_motion_zones_enabled",
        category="motion",
        attr_path="settings.advanced_motion_zones_enabled",
    ),
    RingExtendedSensorDescription(
        key="pir_sensitivity_1",
        translation_key="pir_sensitivity_1",
        category="motion",
        attr_path="settings.pir_sensitivity_1",
    ),
    RingExtendedSensorDescription(
        key="motion_detection_enabled_root",
        translation_key="motion_detection_enabled_root",
        category="motion",
        attr_path="motion_detection_enabled",
    ),
    RingExtendedSensorDescription(
        key="enable_pir_validation",
        translation_key="enable_pir_validation",
        category="motion",
        attr_path="settings.enable_pir_validation",
    ),
    RingExtendedSensorDescription(
        key="enable_rlmd",
        translation_key="enable_rlmd",
        category="motion",
        attr_path="settings.enable_rlmd",
    ),
    RingExtendedSensorDescription(
        key="rlmd_distance",
        translation_key="rlmd_distance",
        category="motion",
        attr_path="settings.rlmd_distance",
    ),
    RingExtendedSensorDescription(
        key="sensitivity",
        translation_key="sensitivity",
        category="motion",
        attr_path="settings.sensitivity",
    ),
    RingExtendedSensorDescription(
        key="active_motion_filter",
        translation_key="active_motion_filter",
        category="motion",
        attr_path="settings.active_motion_filter",
    ),
    RingExtendedSensorDescription(
        key="motion_snooze_privacy_timeout",
        translation_key="motion_snooze_privacy_timeout",
        native_unit_of_measurement=UnitOfTime.SECONDS,
        category="motion",
        attr_path="settings.motion_snooze_privacy_timeout",
    ),
    RingExtendedSensorDescription(
        key="advanced_motion_zones_type",
        translation_key="advanced_motion_zones_type",
        category="motion",
        attr_path="settings.advanced_motion_zones_type",
    ),
    RingExtendedSensorDescription(
        key="motion_announcement",
        translation_key="motion_announcement",
        category="motion",
        attr_path="settings.motion_announcement",
    ),
    # Motion snooze settings
    RingExtendedSensorDescription(
        key="motion_snooze_preset_profile",
        translation_key="motion_snooze_preset_profile",
        category="motion",
        attr_path="settings.motion_settings.motion_snooze_preset_profile",
    ),
    # PIR sensor settings
    RingExtendedSensorDescription(
        key="pir_sensitivity1",
        translation_key="pir_sensitivity1",
        category="motion",
        attr_path="settings.pir_settings.sensitivity1",
    ),
    RingExtendedSensorDescription(
        key="pir_sensitivity2",
        translation_key="pir_sensitivity2",
        category="motion",
        attr_path="settings.pir_settings.sensitivity2",
    ),
    RingExtendedSensorDescription(
        key="pir_sensitivity3",
        translation_key="pir_sensitivity3",
        category="motion",
        attr_path="settings.pir_settings.sensitivity3",
    ),
    RingExtendedSensorDescription(
        key="pir_zone_mask",
        translation_key="pir_zone_mask",
        category="motion",
        attr_path="settings.pir_settings.zone_mask",
    ),
)

# CV Detection Types - these will be generated dynamically
CV_DETECTION_TYPES = [
    "human",
    "motion",
    "other_motion",
    "loitering",
    "moving_vehicle",
    "vehicle",
    "animal",
    "package_delivery",
    "package_pickup",
    "unverified_motion",
    "motion_stop",
    # Sound detection types
    "baby_cry",
    "car_alarm",
    "co2_smoke_alarm",
    "dog_bark",
    "general_sound",
    "glass_break",
]

CV_DETECTION_TYPE_NAMES = {
    "human": "Human",
    "motion": "Motion",
    "other_motion": "Other Motion",
    "loitering": "Loitering",
    "moving_vehicle": "Moving Vehicle",
    "vehicle": "Vehicle",
    "animal": "Animal",
    "package_delivery": "Package Delivery",
    "package_pickup": "Package Pickup",
    "unverified_motion": "Unverified Motion",
    "motion_stop": "Motion Stop",
    # Sound detection types
    "baby_cry": "Baby Cry",
    "car_alarm": "Car Alarm",
    "co2_smoke_alarm": "CO2/Smoke Alarm",
    "dog_bark": "Dog Bark",
    "general_sound": "General Sound",
    "glass_break": "Glass Break",
}


def _create_cv_detection_sensors() -> tuple[RingExtendedSensorDescription, ...]:
    """Create CV detection sensors for all detection types."""
    sensors = []
    for det_type in CV_DETECTION_TYPES:
        base_path = f"settings.cv_settings.detection_types.{det_type}"
        name = CV_DETECTION_TYPE_NAMES[det_type]

        sensors.append(
            RingExtendedSensorDescription(
                key=f"cv_{det_type}_enabled",
                translation_key=f"cv_{det_type}_enabled",
                category="cv_detection",
                attr_path=f"{base_path}.enabled",
            )
        )
        sensors.append(
            RingExtendedSensorDescription(
                key=f"cv_{det_type}_mode",
                translation_key=f"cv_{det_type}_mode",
                category="cv_detection",
                attr_path=f"{base_path}.mode",
            )
        )
        sensors.append(
            RingExtendedSensorDescription(
                key=f"cv_{det_type}_notification",
                translation_key=f"cv_{det_type}_notification",
                category="cv_detection",
                attr_path=f"{base_path}.notification",
            )
        )
        sensors.append(
            RingExtendedSensorDescription(
                key=f"cv_{det_type}_record",
                translation_key=f"cv_{det_type}_record",
                category="cv_detection",
                attr_path=f"{base_path}.record",
            )
        )
    return tuple(sensors)


CV_DETECTION_SENSORS = _create_cv_detection_sensors()

# CV Threshold sensors
CV_THRESHOLD_SENSORS: tuple[RingExtendedSensorDescription, ...] = (
    RingExtendedSensorDescription(
        key="cv_threshold_loitering",
        translation_key="cv_threshold_loitering",
        native_unit_of_measurement=UnitOfTime.SECONDS,
        category="cv_detection",
        attr_path="settings.cv_settings.threshold.loitering",
    ),
    RingExtendedSensorDescription(
        key="cv_threshold_package_delivery",
        translation_key="cv_threshold_package_delivery",
        native_unit_of_measurement=UnitOfTime.SECONDS,
        category="cv_detection",
        attr_path="settings.cv_settings.threshold.package_delivery",
    ),
    RingExtendedSensorDescription(
        key="cv_threshold_unverified_motion",
        translation_key="cv_threshold_unverified_motion",
        native_unit_of_measurement=UnitOfTime.SECONDS,
        category="cv_detection",
        attr_path="settings.cv_settings.threshold.unverified_motion",
    ),
    RingExtendedSensorDescription(
        key="cv_threshold_baby_cry",
        translation_key="cv_threshold_baby_cry",
        native_unit_of_measurement=UnitOfTime.SECONDS,
        category="cv_detection",
        attr_path="settings.cv_settings.threshold.baby_cry",
    ),
    RingExtendedSensorDescription(
        key="cv_threshold_car_alarm",
        translation_key="cv_threshold_car_alarm",
        native_unit_of_measurement=UnitOfTime.SECONDS,
        category="cv_detection",
        attr_path="settings.cv_settings.threshold.car_alarm",
    ),
    RingExtendedSensorDescription(
        key="cv_threshold_co2_smoke_alarm",
        translation_key="cv_threshold_co2_smoke_alarm",
        native_unit_of_measurement=UnitOfTime.SECONDS,
        category="cv_detection",
        attr_path="settings.cv_settings.threshold.co2_smoke_alarm",
    ),
    RingExtendedSensorDescription(
        key="cv_threshold_dog_bark",
        translation_key="cv_threshold_dog_bark",
        native_unit_of_measurement=UnitOfTime.SECONDS,
        category="cv_detection",
        attr_path="settings.cv_settings.threshold.dog_bark",
    ),
    RingExtendedSensorDescription(
        key="cv_threshold_general_sound",
        translation_key="cv_threshold_general_sound",
        native_unit_of_measurement=UnitOfTime.SECONDS,
        category="cv_detection",
        attr_path="settings.cv_settings.threshold.general_sound",
    ),
    RingExtendedSensorDescription(
        key="cv_threshold_glass_break",
        translation_key="cv_threshold_glass_break",
        native_unit_of_measurement=UnitOfTime.SECONDS,
        category="cv_detection",
        attr_path="settings.cv_settings.threshold.glass_break",
    ),
    RingExtendedSensorDescription(
        key="natural_language_search_enabled",
        translation_key="natural_language_search_enabled",
        category="cv_detection",
        attr_path="settings.cv_settings.search_types.natural_language_search.enabled",
    ),
    RingExtendedSensorDescription(
        key="natural_language_search_mode",
        translation_key="natural_language_search_mode",
        category="cv_detection",
        attr_path="settings.cv_settings.search_types.natural_language_search.mode",
    ),
    RingExtendedSensorDescription(
        key="cv_triggers",
        translation_key="cv_triggers",
        category="cv_detection",
        attr_path="settings.cv_paid_features.cv_triggers",
    ),
    # Additional CV thresholds
    RingExtendedSensorDescription(
        key="cv_threshold_motion",
        translation_key="cv_threshold_motion",
        category="cv_detection",
        attr_path="settings.cv_settings.threshold.motion",
    ),
    RingExtendedSensorDescription(
        key="cv_threshold_other_motion",
        translation_key="cv_threshold_other_motion",
        category="cv_detection",
        attr_path="settings.cv_settings.threshold.other_motion",
    ),
    # Advanced object detection settings (CV tuning)
    RingExtendedSensorDescription(
        key="cv_human_confidence_day",
        translation_key="cv_human_confidence_day",
        category="cv_detection",
        attr_path="settings.advanced_object_settings.human_detection_confidence.day",
    ),
    RingExtendedSensorDescription(
        key="cv_human_confidence_night",
        translation_key="cv_human_confidence_night",
        category="cv_detection",
        attr_path="settings.advanced_object_settings.human_detection_confidence.night",
    ),
    RingExtendedSensorDescription(
        key="cv_motion_zone_overlap_day",
        translation_key="cv_motion_zone_overlap_day",
        category="cv_detection",
        attr_path="settings.advanced_object_settings.motion_zone_overlap.day",
    ),
    RingExtendedSensorDescription(
        key="cv_motion_zone_overlap_night",
        translation_key="cv_motion_zone_overlap_night",
        category="cv_detection",
        attr_path="settings.advanced_object_settings.motion_zone_overlap.night",
    ),
    RingExtendedSensorDescription(
        key="cv_object_size_max_day",
        translation_key="cv_object_size_max_day",
        category="cv_detection",
        attr_path="settings.advanced_object_settings.object_size_maximum.day",
    ),
    RingExtendedSensorDescription(
        key="cv_object_size_max_night",
        translation_key="cv_object_size_max_night",
        category="cv_detection",
        attr_path="settings.advanced_object_settings.object_size_maximum.night",
    ),
    RingExtendedSensorDescription(
        key="cv_object_size_min_day",
        translation_key="cv_object_size_min_day",
        category="cv_detection",
        attr_path="settings.advanced_object_settings.object_size_minimum.day",
    ),
    RingExtendedSensorDescription(
        key="cv_object_size_min_night",
        translation_key="cv_object_size_min_night",
        category="cv_detection",
        attr_path="settings.advanced_object_settings.object_size_minimum.night",
    ),
    RingExtendedSensorDescription(
        key="cv_object_time_overlap_day",
        translation_key="cv_object_time_overlap_day",
        category="cv_detection",
        attr_path="settings.advanced_object_settings.object_time_overlap.day",
    ),
    RingExtendedSensorDescription(
        key="cv_object_time_overlap_night",
        translation_key="cv_object_time_overlap_night",
        category="cv_detection",
        attr_path="settings.advanced_object_settings.object_time_overlap.night",
    ),
    # Hybrid motion zones advanced object settings (newer devices)
    RingExtendedSensorDescription(
        key="cv_hybrid_human_confidence_day",
        translation_key="cv_hybrid_human_confidence_day",
        category="cv_detection",
        attr_path="settings.hybrid_motion_zones.advanced_object_settings.human_detection_confidence.day",
    ),
    RingExtendedSensorDescription(
        key="cv_hybrid_human_confidence_night",
        translation_key="cv_hybrid_human_confidence_night",
        category="cv_detection",
        attr_path="settings.hybrid_motion_zones.advanced_object_settings.human_detection_confidence.night",
    ),
    RingExtendedSensorDescription(
        key="cv_hybrid_motion_zone_overlap_day",
        translation_key="cv_hybrid_motion_zone_overlap_day",
        category="cv_detection",
        attr_path="settings.hybrid_motion_zones.advanced_object_settings.motion_zone_overlap.day",
    ),
    RingExtendedSensorDescription(
        key="cv_hybrid_motion_zone_overlap_night",
        translation_key="cv_hybrid_motion_zone_overlap_night",
        category="cv_detection",
        attr_path="settings.hybrid_motion_zones.advanced_object_settings.motion_zone_overlap.night",
    ),
    RingExtendedSensorDescription(
        key="cv_hybrid_object_size_max_day",
        translation_key="cv_hybrid_object_size_max_day",
        category="cv_detection",
        attr_path="settings.hybrid_motion_zones.advanced_object_settings.object_size_maximum.day",
    ),
    RingExtendedSensorDescription(
        key="cv_hybrid_object_size_max_night",
        translation_key="cv_hybrid_object_size_max_night",
        category="cv_detection",
        attr_path="settings.hybrid_motion_zones.advanced_object_settings.object_size_maximum.night",
    ),
    RingExtendedSensorDescription(
        key="cv_hybrid_object_size_min_day",
        translation_key="cv_hybrid_object_size_min_day",
        category="cv_detection",
        attr_path="settings.hybrid_motion_zones.advanced_object_settings.object_size_minimum.day",
    ),
    RingExtendedSensorDescription(
        key="cv_hybrid_object_size_min_night",
        translation_key="cv_hybrid_object_size_min_night",
        category="cv_detection",
        attr_path="settings.hybrid_motion_zones.advanced_object_settings.object_size_minimum.night",
    ),
    RingExtendedSensorDescription(
        key="cv_hybrid_object_time_overlap_day",
        translation_key="cv_hybrid_object_time_overlap_day",
        category="cv_detection",
        attr_path="settings.hybrid_motion_zones.advanced_object_settings.object_time_overlap.day",
    ),
    RingExtendedSensorDescription(
        key="cv_hybrid_object_time_overlap_night",
        translation_key="cv_hybrid_object_time_overlap_night",
        category="cv_detection",
        attr_path="settings.hybrid_motion_zones.advanced_object_settings.object_time_overlap.night",
    ),
)

# CV Paid Features sensors
CV_PAID_SENSORS: tuple[RingExtendedSensorDescription, ...] = (
    RingExtendedSensorDescription(
        key="paid_human",
        translation_key="paid_human",
        category="cv_paid",
        attr_path="settings.cv_paid_features.human",
    ),
    RingExtendedSensorDescription(
        key="paid_motion",
        translation_key="paid_motion",
        category="cv_paid",
        attr_path="settings.cv_paid_features.motion",
    ),
    RingExtendedSensorDescription(
        key="paid_other_motion",
        translation_key="paid_other_motion",
        category="cv_paid",
        attr_path="settings.cv_paid_features.other_motion",
    ),
    RingExtendedSensorDescription(
        key="paid_loitering",
        translation_key="paid_loitering",
        category="cv_paid",
        attr_path="settings.cv_paid_features.loitering",
    ),
    RingExtendedSensorDescription(
        key="paid_vehicle",
        translation_key="paid_vehicle",
        category="cv_paid",
        attr_path="settings.cv_paid_features.vehicle",
    ),
    RingExtendedSensorDescription(
        key="paid_animal",
        translation_key="paid_animal",
        category="cv_paid",
        attr_path="settings.cv_paid_features.animal",
    ),
    RingExtendedSensorDescription(
        key="paid_package_delivery",
        translation_key="paid_package_delivery",
        category="cv_paid",
        attr_path="settings.cv_paid_features.package_delivery",
    ),
    RingExtendedSensorDescription(
        key="paid_package_pickup",
        translation_key="paid_package_pickup",
        category="cv_paid",
        attr_path="settings.cv_paid_features.package_pickup",
    ),
    RingExtendedSensorDescription(
        key="paid_baby_cry",
        translation_key="paid_baby_cry",
        category="cv_paid",
        attr_path="settings.cv_paid_features.baby_cry",
    ),
    RingExtendedSensorDescription(
        key="paid_car_alarm",
        translation_key="paid_car_alarm",
        category="cv_paid",
        attr_path="settings.cv_paid_features.car_alarm",
    ),
    RingExtendedSensorDescription(
        key="paid_co2_smoke_alarm",
        translation_key="paid_co2_smoke_alarm",
        category="cv_paid",
        attr_path="settings.cv_paid_features.co2_smoke_alarm",
    ),
    RingExtendedSensorDescription(
        key="paid_dog_bark",
        translation_key="paid_dog_bark",
        category="cv_paid",
        attr_path="settings.cv_paid_features.dog_bark",
    ),
    RingExtendedSensorDescription(
        key="paid_glass_break",
        translation_key="paid_glass_break",
        category="cv_paid",
        attr_path="settings.cv_paid_features.glass_break",
    ),
    RingExtendedSensorDescription(
        key="paid_general_sound",
        translation_key="paid_general_sound",
        category="cv_paid",
        attr_path="settings.cv_paid_features.general_sound",
    ),
)

# Other Paid Features sensors
OTHER_PAID_SENSORS: tuple[RingExtendedSensorDescription, ...] = (
    RingExtendedSensorDescription(
        key="paid_alexa_concierge",
        translation_key="paid_alexa_concierge",
        category="other_paid",
        attr_path="settings.other_paid_features.alexa_concierge",
    ),
    RingExtendedSensorDescription(
        key="paid_sheila_cv",
        translation_key="paid_sheila_cv",
        category="other_paid",
        attr_path="settings.other_paid_features.sheila_cv",
    ),
    RingExtendedSensorDescription(
        key="paid_sheila_recording",
        translation_key="paid_sheila_recording",
        category="other_paid",
        attr_path="settings.other_paid_features.sheila_recording",
    ),
    RingExtendedSensorDescription(
        key="paid_extended_live_view",
        translation_key="paid_extended_live_view",
        category="other_paid",
        attr_path="settings.other_paid_features.extended_live_view",
    ),
    RingExtendedSensorDescription(
        key="paid_recording_24x7",
        translation_key="paid_recording_24x7",
        category="other_paid",
        attr_path="settings.other_paid_features.recording_24x7",
    ),
    RingExtendedSensorDescription(
        key="paid_natural_language_search",
        translation_key="paid_natural_language_search",
        category="other_paid",
        attr_path="settings.other_paid_features.natural_language_search",
    ),
    RingExtendedSensorDescription(
        key="paid_multicam_live_view",
        translation_key="paid_multicam_live_view",
        category="other_paid",
        attr_path="settings.other_paid_features.multicam_live_view",
    ),
    RingExtendedSensorDescription(
        key="paid_daily_digest",
        translation_key="paid_daily_digest",
        category="other_paid",
        attr_path="settings.other_paid_features.daily_digest",
    ),
    RingExtendedSensorDescription(
        key="paid_package_protection",
        translation_key="paid_package_protection",
        category="other_paid",
        attr_path="settings.other_paid_features.package_protection",
    ),
    RingExtendedSensorDescription(
        key="paid_critical_alerts",
        translation_key="paid_critical_alerts",
        category="other_paid",
        attr_path="settings.other_paid_features.critical_alerts",
    ),
    RingExtendedSensorDescription(
        key="paid_alarm_triggered_recording",
        translation_key="paid_alarm_triggered_recording",
        category="other_paid",
        attr_path="settings.other_paid_features.alarm_triggered_recording",
    ),
    RingExtendedSensorDescription(
        key="paid_closed_caption",
        translation_key="paid_closed_caption",
        category="other_paid",
        attr_path="settings.other_paid_features.closed_caption",
    ),
    RingExtendedSensorDescription(
        key="paid_ding_call",
        translation_key="paid_ding_call",
        category="other_paid",
        attr_path="settings.other_paid_features.ding_call",
    ),
    RingExtendedSensorDescription(
        key="paid_live_speak",
        translation_key="paid_live_speak",
        category="other_paid",
        attr_path="settings.other_paid_features.live_speak",
    ),
    RingExtendedSensorDescription(
        key="paid_snapshot_capture_plus",
        translation_key="paid_snapshot_capture_plus",
        category="other_paid",
        attr_path="settings.other_paid_features.snapshot_capture_plus",
    ),
    RingExtendedSensorDescription(
        key="paid_system_level_pip",
        translation_key="paid_system_level_pip",
        category="other_paid",
        attr_path="settings.other_paid_features.system_level_pip",
    ),
)

# Notification sensors
NOTIFICATION_SENSORS: tuple[RingExtendedSensorDescription, ...] = (
    RingExtendedSensorDescription(
        key="enable_rich_notifications",
        translation_key="enable_rich_notifications",
        category="notifications",
        attr_path="settings.enable_rich_notifications",
    ),
    RingExtendedSensorDescription(
        key="rich_notifications_billing_eligible",
        translation_key="rich_notifications_billing_eligible",
        category="notifications",
        attr_path="settings.rich_notifications_billing_eligible",
    ),
    RingExtendedSensorDescription(
        key="rich_notifications_face_crop_enabled",
        translation_key="rich_notifications_face_crop_enabled",
        category="notifications",
        attr_path="settings.rich_notifications_face_crop_enabled",
    ),
    RingExtendedSensorDescription(
        key="rich_notifications_scene_source",
        translation_key="rich_notifications_scene_source",
        category="notifications",
        attr_path="settings.rich_notifications_scene_source",
    ),
    RingExtendedSensorDescription(
        key="rich_notifications_eligible",
        translation_key="rich_notifications_eligible",
        category="notifications",
        attr_path="features.rich_notifications_eligible",
    ),
    RingExtendedSensorDescription(
        key="concierge_mode",
        translation_key="concierge_mode",
        category="notifications",
        attr_path="settings.concierge_settings.mode",
    ),
    RingExtendedSensorDescription(
        key="concierge_alexa_delay_ms",
        translation_key="concierge_alexa_delay_ms",
        native_unit_of_measurement="ms",
        category="notifications",
        attr_path="settings.concierge_settings.alexa_settings.delay_ms",
    ),
    RingExtendedSensorDescription(
        key="concierge_autoreply_delay_ms",
        translation_key="concierge_autoreply_delay_ms",
        native_unit_of_measurement="ms",
        category="notifications",
        attr_path="settings.concierge_settings.autoreply_settings.delay_ms",
    ),
)

# Recording & Storage sensors
RECORDING_SENSORS: tuple[RingExtendedSensorDescription, ...] = (
    RingExtendedSensorDescription(
        key="user_specified_recording_ttl",
        translation_key="user_specified_recording_ttl",
        native_unit_of_measurement="days",
        category="recording",
        attr_path="settings.user_specified_recording_ttl",
    ),
    RingExtendedSensorDescription(
        key="lite_24x7_subscribed",
        translation_key="lite_24x7_subscribed",
        category="recording",
        attr_path="settings.lite_24x7.subscribed",
    ),
    RingExtendedSensorDescription(
        key="lite_24x7_enabled",
        translation_key="lite_24x7_enabled",
        category="recording",
        attr_path="settings.lite_24x7.enabled",
    ),
    RingExtendedSensorDescription(
        key="lite_24x7_frequency_secs",
        translation_key="lite_24x7_frequency_secs",
        native_unit_of_measurement=UnitOfTime.SECONDS,
        category="recording",
        attr_path="settings.lite_24x7.frequency_secs",
    ),
    RingExtendedSensorDescription(
        key="lite_24x7_resolution_p",
        translation_key="lite_24x7_resolution_p",
        native_unit_of_measurement="p",
        category="recording",
        attr_path="settings.lite_24x7.resolution_p",
    ),
    RingExtendedSensorDescription(
        key="lite_24x7_footage_ttl",
        translation_key="lite_24x7_footage_ttl",
        native_unit_of_measurement=UnitOfTime.HOURS,
        category="recording",
        attr_path="settings.lite_24x7_footage_ttl",
    ),
    RingExtendedSensorDescription(
        key="offline_motion_enabled",
        translation_key="offline_motion_enabled",
        category="recording",
        attr_path="settings.offline_motion_event_settings.enabled",
    ),
    RingExtendedSensorDescription(
        key="lite_24x7_frequency_secs_powered",
        translation_key="lite_24x7_frequency_secs_powered",
        native_unit_of_measurement=UnitOfTime.SECONDS,
        category="recording",
        attr_path="settings.lite_24x7.frequency_secs_powered",
    ),
    RingExtendedSensorDescription(
        key="data_collection_enabled",
        translation_key="data_collection_enabled",
        category="recording",
        attr_path="settings.data_collection_enabled",
    ),
    RingExtendedSensorDescription(
        key="offline_motion_frequency_after_secs",
        translation_key="offline_motion_frequency_after_secs",
        native_unit_of_measurement=UnitOfTime.SECONDS,
        category="recording",
        attr_path="settings.offline_motion_event_settings.frequency_after_secs",
    ),
    RingExtendedSensorDescription(
        key="offline_motion_max_upload_kb",
        translation_key="offline_motion_max_upload_kb",
        native_unit_of_measurement="KB",
        category="recording",
        attr_path="settings.offline_motion_event_settings.max_upload_kb",
    ),
    RingExtendedSensorDescription(
        key="offline_motion_period_after_secs",
        translation_key="offline_motion_period_after_secs",
        native_unit_of_measurement=UnitOfTime.SECONDS,
        category="recording",
        attr_path="settings.offline_motion_event_settings.period_after_secs",
    ),
    RingExtendedSensorDescription(
        key="offline_motion_resolution_p",
        translation_key="offline_motion_resolution_p",
        native_unit_of_measurement="p",
        category="recording",
        attr_path="settings.offline_motion_event_settings.resolution_p",
    ),
    RingExtendedSensorDescription(
        key="offline_motion_subscribed",
        translation_key="offline_motion_subscribed",
        category="recording",
        attr_path="settings.offline_motion_event_settings.subscribed",
    ),
    # Snapshot settings
    RingExtendedSensorDescription(
        key="snapshot_frequency_secs",
        translation_key="snapshot_frequency_secs",
        native_unit_of_measurement=UnitOfTime.SECONDS,
        category="recording",
        attr_path="settings.snapshot_settings.frequency_secs",
    ),
    RingExtendedSensorDescription(
        key="snapshot_frequency_secs_powered",
        translation_key="snapshot_frequency_secs_powered",
        native_unit_of_measurement=UnitOfTime.SECONDS,
        category="recording",
        attr_path="settings.snapshot_settings.frequency_secs_powered",
    ),
    RingExtendedSensorDescription(
        key="snapshot_frequency_after_secs",
        translation_key="snapshot_frequency_after_secs",
        native_unit_of_measurement=UnitOfTime.SECONDS,
        category="recording",
        attr_path="settings.snapshot_settings.frequency_after_secs",
    ),
    RingExtendedSensorDescription(
        key="snapshot_period_after_secs",
        translation_key="snapshot_period_after_secs",
        native_unit_of_measurement=UnitOfTime.SECONDS,
        category="recording",
        attr_path="settings.snapshot_settings.period_after_secs",
    ),
    RingExtendedSensorDescription(
        key="snapshot_max_upload_kb",
        translation_key="snapshot_max_upload_kb",
        native_unit_of_measurement="KB",
        category="recording",
        attr_path="settings.snapshot_settings.max_upload_kb",
    ),
    RingExtendedSensorDescription(
        key="snapshot_lite_24x7_resolution_p",
        translation_key="snapshot_lite_24x7_resolution_p",
        native_unit_of_measurement="p",
        category="recording",
        attr_path="settings.snapshot_settings.lite_24x7_resolution_p",
    ),
    RingExtendedSensorDescription(
        key="snapshot_ome_resolution_p",
        translation_key="snapshot_ome_resolution_p",
        native_unit_of_measurement="p",
        category="recording",
        attr_path="settings.snapshot_settings.ome_resolution_p",
    ),
    RingExtendedSensorDescription(
        key="snapshot_close_container",
        translation_key="snapshot_close_container",
        category="recording",
        attr_path="settings.snapshot_settings.close_container",
    ),
    RingExtendedSensorDescription(
        key="snapshot_limited_network_rich_notifications",
        translation_key="snapshot_limited_network_rich_notifications",
        category="recording",
        attr_path="settings.snapshot_settings.enable_limited_network_rich_notifications",
    ),
)

# Floodlight sensors
FLOODLIGHT_SENSORS: tuple[RingExtendedSensorDescription, ...] = (
    RingExtendedSensorDescription(
        key="floodlight_on",
        translation_key="floodlight_on",
        category="floodlight",
        attr_path="health.floodlight_on",
    ),
    RingExtendedSensorDescription(
        key="white_led_on",
        translation_key="white_led_on",
        category="floodlight",
        attr_path="health.white_led_on",
    ),
    RingExtendedSensorDescription(
        key="floodlight_duration",
        translation_key="floodlight_duration",
        native_unit_of_measurement=UnitOfTime.SECONDS,
        device_class=SensorDeviceClass.DURATION,
        category="floodlight",
        attr_path="settings.floodlight_settings.duration",
    ),
    RingExtendedSensorDescription(
        key="floodlight_brightness",
        translation_key="floodlight_brightness",
        category="floodlight",
        attr_path="settings.floodlight_settings.brightness",
    ),
    RingExtendedSensorDescription(
        key="floodlight_always_on",
        translation_key="floodlight_always_on",
        category="floodlight",
        attr_path="settings.floodlight_settings.always_on",
    ),
    RingExtendedSensorDescription(
        key="light_settings",
        translation_key="light_settings",
        category="floodlight",
        attr_path="settings.light_settings",
    ),
    RingExtendedSensorDescription(
        key="ir_led_settings",
        translation_key="ir_led_settings",
        category="floodlight",
        attr_path="settings.ir_led_settings",
    ),
    # Additional floodlight settings
    RingExtendedSensorDescription(
        key="floodlight_adaptive_brightness_enabled",
        translation_key="floodlight_adaptive_brightness_enabled",
        category="floodlight",
        attr_path="settings.floodlight_settings.adaptive_lights_brightness_enabled",
    ),
    RingExtendedSensorDescription(
        key="floodlight_always_on_duration",
        translation_key="floodlight_always_on_duration",
        native_unit_of_measurement=UnitOfTime.MINUTES,
        category="floodlight",
        attr_path="settings.floodlight_settings.always_on_duration",
    ),
    RingExtendedSensorDescription(
        key="floodlight_priority",
        translation_key="floodlight_priority",
        category="floodlight",
        attr_path="settings.floodlight_settings.priority",
    ),
    # Light snooze settings
    RingExtendedSensorDescription(
        key="light_snooze_always_on",
        translation_key="light_snooze_always_on",
        category="floodlight",
        attr_path="settings.light_snooze_settings.always_on",
    ),
    RingExtendedSensorDescription(
        key="light_snooze_duration",
        translation_key="light_snooze_duration",
        native_unit_of_measurement=UnitOfTime.MINUTES,
        category="floodlight",
        attr_path="settings.light_snooze_settings.duration",
    ),
)

# Radar / Bird's Eye View sensors
RADAR_SENSORS: tuple[RingExtendedSensorDescription, ...] = (
    RingExtendedSensorDescription(
        key="birds_eye_view_enabled",
        translation_key="birds_eye_view_enabled",
        category="radar",
        attr_path="settings.radar_settings.birds_eye_view_enabled",
    ),
    RingExtendedSensorDescription(
        key="bez_feature_enabled",
        translation_key="bez_feature_enabled",
        category="radar",
        attr_path="settings.radar_settings.bez_feature_enabled",
    ),
    RingExtendedSensorDescription(
        key="bez_filtering_enabled",
        translation_key="bez_filtering_enabled",
        category="radar",
        attr_path="settings.radar_settings.bez_filtering_enabled",
    ),
    RingExtendedSensorDescription(
        key="installation_height",
        translation_key="installation_height",
        native_unit_of_measurement="m",
        category="radar",
        attr_path="settings.radar_settings.installation_height",
    ),
    RingExtendedSensorDescription(
        key="auto_motion_sensitivity_enabled",
        translation_key="auto_motion_sensitivity_enabled",
        category="radar",
        attr_path="settings.radar_settings.auto_motion_sensitivity_enabled",
    ),
)

# Local Processing (Sheila) sensors
LOCAL_PROCESSING_SENSORS: tuple[RingExtendedSensorDescription, ...] = (
    RingExtendedSensorDescription(
        key="sheila_cv_processing_enabled",
        translation_key="sheila_cv_processing_enabled",
        category="local_processing",
        attr_path="settings.sheila_settings.cv_processing_enabled",
    ),
    RingExtendedSensorDescription(
        key="sheila_local_storage_enabled",
        translation_key="sheila_local_storage_enabled",
        category="local_processing",
        attr_path="settings.sheila_settings.local_storage_enabled",
    ),
    RingExtendedSensorDescription(
        key="sheila_camera_eligible",
        translation_key="sheila_camera_eligible",
        category="local_processing",
        attr_path="features.sheila_camera_eligible",
    ),
    RingExtendedSensorDescription(
        key="sheila_camera_processing_eligible",
        translation_key="sheila_camera_processing_eligible",
        category="local_processing",
        attr_path="features.sheila_camera_processing_eligible",
    ),
    RingExtendedSensorDescription(
        key="stark_enabled",
        translation_key="stark_enabled",
        category="local_processing",
        attr_path="settings.stark_enabled",
    ),
    RingExtendedSensorDescription(
        key="stark_enrolled",
        translation_key="stark_enrolled",
        category="local_processing",
        attr_path="settings.stark_enrolled",
    ),
)

# Feature Eligibility sensors
FEATURE_SENSORS: tuple[RingExtendedSensorDescription, ...] = (
    RingExtendedSensorDescription(
        key="cfes_eligible",
        translation_key="cfes_eligible",
        category="features",
        attr_path="features.cfes_eligible",
    ),
    RingExtendedSensorDescription(
        key="motions_enabled",
        translation_key="motions_enabled",
        category="features",
        attr_path="features.motions_enabled",
    ),
    RingExtendedSensorDescription(
        key="show_recordings",
        translation_key="show_recordings",
        category="features",
        attr_path="features.show_recordings",
    ),
    RingExtendedSensorDescription(
        key="show_vod_settings",
        translation_key="show_vod_settings",
        category="features",
        attr_path="features.show_vod_settings",
    ),
    RingExtendedSensorDescription(
        key="recording_mode",
        translation_key="recording_mode",
        category="features",
        attr_path="features.video_recording.recording_mode",
    ),
    RingExtendedSensorDescription(
        key="recording_enabled",
        translation_key="recording_enabled",
        category="features",
        attr_path="features.video_recording.recording_enabled",
    ),
    RingExtendedSensorDescription(
        key="recording_state",
        translation_key="recording_state",
        category="features",
        attr_path="features.video_recording.recording_state",
    ),
    RingExtendedSensorDescription(
        key="recording_24x7_eligible",
        translation_key="recording_24x7_eligible",
        category="features",
        attr_path="features.recording_24x7_eligible",
    ),
    RingExtendedSensorDescription(
        key="dynamic_network_switching_eligible",
        translation_key="dynamic_network_switching_eligible",
        category="features",
        attr_path="features.dynamic_network_switching_eligible",
    ),
    RingExtendedSensorDescription(
        key="advanced_motion_enabled",
        translation_key="advanced_motion_enabled",
        category="features",
        attr_path="features.advanced_motion_enabled",
    ),
    RingExtendedSensorDescription(
        key="ai_warnings_eligible",
        translation_key="ai_warnings_eligible",
        category="features",
        attr_path="features.ai_automated_warnings.eligibility.eligible",
    ),
    RingExtendedSensorDescription(
        key="ai_warnings_allowed",
        translation_key="ai_warnings_allowed",
        category="features",
        attr_path="features.ai_automated_warnings.enablement.allowed",
    ),
    RingExtendedSensorDescription(
        key="ai_warnings_enabled",
        translation_key="ai_warnings_enabled",
        category="features",
        attr_path="features.ai_automated_warnings.enablement.enabled",
    ),
    RingExtendedSensorDescription(
        key="alexa_greetings_eligible",
        translation_key="alexa_greetings_eligible",
        category="features",
        attr_path="features.alexa_plus_greetings.eligibility.eligible",
    ),
    RingExtendedSensorDescription(
        key="alexa_greetings_allowed",
        translation_key="alexa_greetings_allowed",
        category="features",
        attr_path="features.alexa_plus_greetings.enablement.allowed",
    ),
    RingExtendedSensorDescription(
        key="alexa_greetings_enabled",
        translation_key="alexa_greetings_enabled",
        category="features",
        attr_path="features.alexa_plus_greetings.enablement.enabled",
    ),
    RingExtendedSensorDescription(
        key="animal_detection_eligible",
        translation_key="animal_detection_eligible",
        category="features",
        attr_path="features.animal_detection_eligible",
    ),
    RingExtendedSensorDescription(
        key="chime_auto_detect_capable",
        translation_key="chime_auto_detect_capable",
        category="features",
        attr_path="features.chime_auto_detect_capable",
    ),
    RingExtendedSensorDescription(
        key="chime_settings_eligible",
        translation_key="chime_settings_eligible",
        category="features",
        attr_path="features.chime_settings.is_eligible",
    ),
    RingExtendedSensorDescription(
        key="light_schedule_enabled",
        translation_key="light_schedule_enabled",
        category="features",
        attr_path="features.light_schedule_enabled",
    ),
    RingExtendedSensorDescription(
        key="live_view_audio_privacy_eligible",
        translation_key="live_view_audio_privacy_eligible",
        category="features",
        attr_path="features.live_view_audio_privacy_controls.eligibility.eligible",
    ),
    RingExtendedSensorDescription(
        key="live_view_pip_mode",
        translation_key="live_view_pip_mode",
        category="features",
        attr_path="features.live_view_pip_mode",
    ),
    RingExtendedSensorDescription(
        key="motion_message_enabled",
        translation_key="motion_message_enabled",
        category="features",
        attr_path="features.motion_message_enabled",
    ),
    RingExtendedSensorDescription(
        key="motion_stop_edge_eligible",
        translation_key="motion_stop_edge_eligible",
        category="features",
        attr_path="features.motion_stop_edge_eligible",
    ),
    RingExtendedSensorDescription(
        key="motion_zone_recommendation",
        translation_key="motion_zone_recommendation",
        category="features",
        attr_path="features.motion_zone_recommendation",
    ),
    RingExtendedSensorDescription(
        key="multiple_detection_events_enabled",
        translation_key="multiple_detection_events_enabled",
        category="features",
        attr_path="features.multiple_detection_events.enabled",
    ),
    RingExtendedSensorDescription(
        key="night_vision_enabled",
        translation_key="night_vision_enabled",
        category="features",
        attr_path="features.night_vision_enabled",
    ),
    RingExtendedSensorDescription(
        key="package_warning_activation_eligible",
        translation_key="package_warning_activation_eligible",
        category="features",
        attr_path="features.package_warning.activation_eligible",
    ),
    RingExtendedSensorDescription(
        key="package_warning_active",
        translation_key="package_warning_active",
        category="features",
        attr_path="features.package_warning.active",
    ),
    RingExtendedSensorDescription(
        key="package_warning_automation_eligible",
        translation_key="package_warning_automation_eligible",
        category="features",
        attr_path="features.package_warning.automation_eligible",
    ),
    RingExtendedSensorDescription(
        key="package_warning_enabled",
        translation_key="package_warning_enabled",
        category="features",
        attr_path="features.package_warning.enabled",
    ),
    RingExtendedSensorDescription(
        key="people_only_enabled",
        translation_key="people_only_enabled",
        category="features",
        attr_path="features.people_only_enabled",
    ),
    RingExtendedSensorDescription(
        key="person_id_eligible",
        translation_key="person_id_eligible",
        category="features",
        attr_path="features.person_identification.eligibility.eligible",
    ),
    RingExtendedSensorDescription(
        key="person_id_allowed",
        translation_key="person_id_allowed",
        category="features",
        attr_path="features.person_identification.enablement.allowed",
    ),
    RingExtendedSensorDescription(
        key="person_id_enabled",
        translation_key="person_id_enabled",
        category="features",
        attr_path="features.person_identification.enablement.enabled",
    ),
    RingExtendedSensorDescription(
        key="ptz_setup_complete",
        translation_key="ptz_setup_complete",
        category="features",
        attr_path="features.ptz_setup_complete",
    ),
    RingExtendedSensorDescription(
        key="retinal_tuning_eligible",
        translation_key="retinal_tuning_eligible",
        category="features",
        attr_path="features.retinal_tuning.eligibility.eligible",
    ),
    RingExtendedSensorDescription(
        key="retinal_tuning_allowed",
        translation_key="retinal_tuning_allowed",
        category="features",
        attr_path="features.retinal_tuning.enablement.allowed",
    ),
    RingExtendedSensorDescription(
        key="retinal_tuning_enabled",
        translation_key="retinal_tuning_enabled",
        category="features",
        attr_path="features.retinal_tuning.enablement.enabled",
    ),
    RingExtendedSensorDescription(
        key="retinal_tuning_max_zoom",
        translation_key="retinal_tuning_max_zoom",
        category="features",
        attr_path="features.retinal_tuning.rt_max_digital_zoom_level",
    ),
    RingExtendedSensorDescription(
        key="shadow_correction_enabled",
        translation_key="shadow_correction_enabled",
        category="features",
        attr_path="features.shadow_correction_enabled",
    ),
    RingExtendedSensorDescription(
        key="show_24x7_lite",
        translation_key="show_24x7_lite",
        category="features",
        attr_path="features.show_24x7_lite",
    ),
    RingExtendedSensorDescription(
        key="show_offline_motion_events",
        translation_key="show_offline_motion_events",
        category="features",
        attr_path="features.show_offline_motion_events",
    ),
    RingExtendedSensorDescription(
        key="show_radar_data",
        translation_key="show_radar_data",
        category="features",
        attr_path="features.show_radar_data",
    ),
    RingExtendedSensorDescription(
        key="single_alert_eligible",
        translation_key="single_alert_eligible",
        category="features",
        attr_path="features.single_alert.eligibility.eligible",
    ),
    RingExtendedSensorDescription(
        key="single_alert_allowed",
        translation_key="single_alert_allowed",
        category="features",
        attr_path="features.single_alert.enablement.allowed",
    ),
    RingExtendedSensorDescription(
        key="single_alert_enabled",
        translation_key="single_alert_enabled",
        category="features",
        attr_path="features.single_alert.enablement.enabled",
    ),
    RingExtendedSensorDescription(
        key="transformer_score_features",
        translation_key="transformer_score_features",
        category="features",
        attr_path="features.transformer_score.score",
    ),
    RingExtendedSensorDescription(
        key="unusual_alert_eligible",
        translation_key="unusual_alert_eligible",
        category="features",
        attr_path="features.unusual_alert.eligibility.eligible",
    ),
    RingExtendedSensorDescription(
        key="unusual_alert_allowed",
        translation_key="unusual_alert_allowed",
        category="features",
        attr_path="features.unusual_alert.enablement.allowed",
    ),
    RingExtendedSensorDescription(
        key="unusual_alert_enabled",
        translation_key="unusual_alert_enabled",
        category="features",
        attr_path="features.unusual_alert.enablement.enabled",
    ),
    RingExtendedSensorDescription(
        key="unusual_alert_learning_state",
        translation_key="unusual_alert_learning_state",
        category="features",
        attr_path="features.unusual_alert.learning.state",
    ),
    RingExtendedSensorDescription(
        key="vehicle_detection_eligible",
        translation_key="vehicle_detection_eligible",
        category="features",
        attr_path="features.vehicle_detection_eligible",
    ),
    RingExtendedSensorDescription(
        key="video_donation_eligible",
        translation_key="video_donation_eligible",
        category="features",
        attr_path="features.video_donation.eligibility.eligible",
    ),
    RingExtendedSensorDescription(
        key="continuous_recording_available",
        translation_key="continuous_recording_available",
        category="features",
        attr_path="features.video_recording.recording_mode_availability.continuous.available",
    ),
    RingExtendedSensorDescription(
        key="continuous_recording_supported",
        translation_key="continuous_recording_supported",
        category="features",
        attr_path="features.video_recording.recording_mode_availability.continuous.supported",
    ),
    RingExtendedSensorDescription(
        key="smart_video_description_eligible",
        translation_key="smart_video_description_eligible",
        category="features",
        attr_path="features.smart_video_description.eligibility.eligible",
    ),
    RingExtendedSensorDescription(
        key="smart_video_description_allowed",
        translation_key="smart_video_description_allowed",
        category="features",
        attr_path="features.smart_video_description.enablement.allowed",
    ),
    RingExtendedSensorDescription(
        key="smart_video_description_enabled",
        translation_key="smart_video_description_enabled",
        category="features",
        attr_path="features.smart_video_description.enablement.enabled",
    ),
    RingExtendedSensorDescription(
        key="smart_video_search_eligible",
        translation_key="smart_video_search_eligible",
        category="features",
        attr_path="features.smart_video_search.eligibility.eligible",
    ),
    RingExtendedSensorDescription(
        key="smart_video_search_allowed",
        translation_key="smart_video_search_allowed",
        category="features",
        attr_path="features.smart_video_search.enablement.allowed",
    ),
    RingExtendedSensorDescription(
        key="smart_video_search_enabled",
        translation_key="smart_video_search_enabled",
        category="features",
        attr_path="features.smart_video_search.enablement.enabled",
    ),
    RingExtendedSensorDescription(
        key="continuous_recording_unavailability_reason",
        translation_key="continuous_recording_unavailability_reason",
        category="features",
        attr_path="features.video_recording.recording_mode_availability.continuous.unavailability_reason",
    ),
)

# Device Status sensors
DEVICE_STATUS_SENSORS: tuple[RingExtendedSensorDescription, ...] = (
    RingExtendedSensorDescription(
        key="night_mode_on",
        translation_key="night_mode_on",
        category="device_status",
        attr_path="health.night_mode_on",
    ),
    RingExtendedSensorDescription(
        key="siren_on",
        translation_key="siren_on",
        category="device_status",
        attr_path="health.siren_on",
    ),
    RingExtendedSensorDescription(
        key="hatch_open",
        translation_key="hatch_open",
        category="device_status",
        attr_path="health.hatch_open",
    ),
    RingExtendedSensorDescription(
        key="stolen",
        translation_key="stolen",
        category="device_status",
        attr_path="stolen",
    ),
    RingExtendedSensorDescription(
        key="owned",
        translation_key="owned",
        category="device_status",
        attr_path="owned",
    ),
    RingExtendedSensorDescription(
        key="subscribed",
        translation_key="subscribed",
        category="device_status",
        attr_path="subscribed",
    ),
    RingExtendedSensorDescription(
        key="is_sidewalk_gateway",
        translation_key="is_sidewalk_gateway",
        category="device_status",
        attr_path="is_sidewalk_gateway",
    ),
    RingExtendedSensorDescription(
        key="device_kind",
        translation_key="device_kind",
        category="device_status",
        attr_path="kind",
    ),
    RingExtendedSensorDescription(
        key="led_status",
        translation_key="led_status",
        category="device_status",
        attr_path="led_status",
    ),
    RingExtendedSensorDescription(
        key="night_mode_status",
        translation_key="night_mode_status",
        category="device_status",
        attr_path="night_mode_status",
    ),
    RingExtendedSensorDescription(
        key="siren_seconds_remaining",
        translation_key="siren_seconds_remaining",
        native_unit_of_measurement=UnitOfTime.SECONDS,
        category="device_status",
        attr_path="siren_status.seconds_remaining",
    ),
    RingExtendedSensorDescription(
        key="subscribed_motions",
        translation_key="subscribed_motions",
        category="device_status",
        attr_path="subscribed_motions",
    ),
    RingExtendedSensorDescription(
        key="time_zone",
        translation_key="time_zone",
        category="device_status",
        attr_path="time_zone",
    ),
    RingExtendedSensorDescription(
        key="created_at",
        translation_key="created_at",
        category="device_status",
        attr_path="created_at",
    ),
    RingExtendedSensorDescription(
        key="active_streaming_event_led",
        translation_key="active_streaming_event_led",
        category="device_status",
        attr_path="settings.active_streaming_event_led_enabled",
    ),
    RingExtendedSensorDescription(
        key="device_placement_info",
        translation_key="device_placement_info",
        category="device_status",
        attr_path="settings.device_placement_info",
    ),
    RingExtendedSensorDescription(
        key="flick_elim_recommended_mode",
        translation_key="flick_elim_recommended_mode",
        category="device_status",
        attr_path="settings.flick_elim_recommended_mode",
    ),
    RingExtendedSensorDescription(
        key="max_resolution_mode_eligible",
        translation_key="max_resolution_mode_eligible",
        category="device_status",
        attr_path="settings.max_resolution_mode_eligible",
    ),
    RingExtendedSensorDescription(
        key="terms_of_service_accepted",
        translation_key="terms_of_service_accepted",
        category="device_status",
        attr_path="settings.terms_of_service_accepted",
    ),
    # Device metadata
    RingExtendedSensorDescription(
        key="hardware_id",
        translation_key="hardware_id",
        category="device_status",
        attr_path="hardware_id",
    ),
    RingExtendedSensorDescription(
        key="ring_net_id",
        translation_key="ring_net_id",
        category="device_status",
        attr_path="ring_net_id",
    ),
    RingExtendedSensorDescription(
        key="is_sidewalk_gateway",
        translation_key="is_sidewalk_gateway",
        category="device_status",
        attr_path="metadata.is_sidewalk_gateway",
    ),
    RingExtendedSensorDescription(
        key="imported_from_amazon",
        translation_key="imported_from_amazon",
        category="device_status",
        attr_path="metadata.imported_from_amazon",
    ),
    RingExtendedSensorDescription(
        key="legacy_fw_migrated",
        translation_key="legacy_fw_migrated",
        category="device_status",
        attr_path="metadata.legacy_fw_migrated",
    ),
    RingExtendedSensorDescription(
        key="third_party_manufacturer",
        translation_key="third_party_manufacturer",
        category="device_status",
        attr_path="metadata.third_party_manufacturer",
    ),
    RingExtendedSensorDescription(
        key="third_party_model",
        translation_key="third_party_model",
        category="device_status",
        attr_path="metadata.third_party_model",
    ),
)

# Mapping of categories to their sensor definitions
CATEGORY_SENSORS: dict[str, tuple[RingExtendedSensorDescription, ...]] = {
    "health": HEALTH_SENSORS,
    "power": POWER_SENSORS,
    "firmware": FIRMWARE_SENSORS,
    "video": VIDEO_SENSORS,
    "audio": AUDIO_SENSORS,
    "motion": MOTION_SENSORS,
    "cv_detection": CV_DETECTION_SENSORS + CV_THRESHOLD_SENSORS,
    "cv_paid": CV_PAID_SENSORS,
    "other_paid": OTHER_PAID_SENSORS,
    "notifications": NOTIFICATION_SENSORS,
    "recording": RECORDING_SENSORS,
    "floodlight": FLOODLIGHT_SENSORS,
    "radar": RADAR_SENSORS,
    "local_processing": LOCAL_PROCESSING_SENSORS,
    "features": FEATURE_SENSORS,
    "device_status": DEVICE_STATUS_SENSORS,
}

# All sensors combined
ALL_SENSORS: tuple[RingExtendedSensorDescription, ...] = tuple(
    sensor for sensors in CATEGORY_SENSORS.values() for sensor in sensors
)
